---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# create a cluster with the local registry enabled in containerd
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /proc
        containerPath: /proc-host
      - hostPath: /usr/src
        containerPath: /usr/src