apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kepler-clusterrole
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics # access /metrics/resource
  - nodes/proxy
  - nodes/stats
  - pods
  verbs:
  - 'get'
  - 'watch'
  - 'list'