---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler-exporter
  namespace: kepler
spec:
  template:
    spec:
      containers:
      - name: kepler-exporter
        volumeMounts:
        - mountPath: /usr/src
          name: usr-src
      volumes:
      - name: usr-src
        hostPath:
          path: /usr/src
          type: Directory
