include-title: false
include-commits: true
label-mapping:
  fix: [fix, bugfix]
  feat: [feat, feature]
  chore: [chore]
  docs: [docs, documentation]
  test: [test]
  refactor: [refactor]
  ci: [ci]
  perf: [perf]
  revert: [revert]
