{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "tags": [
  "kepler",
  "energy consumption"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pod_energy_stat, pod_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pod_energy_stat{pod_namespace=\"$namespace\"}, pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Current Energy Consumption (mW)",
   "type": "timeseries",
   "description": "The mW per minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pod_energy_current{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/20",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(pod_cpu_energy_current{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/20",
     "legendFormat": "CPU"
    },
    {
     "expr": "rate(pod_dram_energy_current{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/20",
     "legendFormat": "DRAM"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW) in 24hrs",
   "type": "timeseries",
   "description": "Total kW Consumed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pod_energy_total{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "TOTAL {{pod_name}}"
    },
    {
     "expr": "rate(pod_cpu_energy_total{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "CPU {{pod_name}}"
    },
    {
     "expr": "rate(pod_dram_energy_total{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "DRAM {{pod_name}}"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW) in $namespace in 24hrs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pod_energy_total{pod_namespace=\"$namespace\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption (kW) by Namespace in 24hrs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (pod_namespace) (\n    rate(pod_energy_total[24h])/(20*60*24)/3600000000\n) "
    }
   ]
  }
 ]
}