# SPDX-FileCopyrightText: 2025 The Kepler Authors
# SPDX-License-Identifier: Apache-2.0

coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 70%

ignore:
  - internal/device/gpu/nvidia/nvml_lib.go
