{
 "title": "Latest vs Development",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "process",
    "query": {
     "query": "query_result(count by (pid, command) (kepler_process_bpf_block_irq_total{job=\"latest\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latest / Platform Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kepler_node_platform_joules_total{job=\"latest\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dev / Platform Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(kepler_node_platform_joules_total{job=\"dev\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest / Process ${process} Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kepler_process_package_joules_total{job=\"latest\", pid=\"${process}\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dev / Process ${process} Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(kepler_process_package_joules_total{job=\"dev\", pid=\"${process}\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}