---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Kepler exporter"
    openshift.io/display-name: ""
  name: kepler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kepler-clusterrole
  namespace: kepler
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics # access /metrics/resource
  - nodes/proxy # access /pods
  - nodes/stats # access /pods
  verbs:
  - 'get'
  - 'watch'
  - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kepler-clusterrole-binding
  namespace: kepler
roleRef:
  kind: ClusterRole
  name: kepler-clusterrole
  apiGroup: "rbac.authorization.k8s.io"
subjects:
- kind: ServiceAccount
  name: kepler-sa
  namespace: kepler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kepler-sa
  namespace: kepler
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler-exporter
  namespace: kepler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kepler-exporter
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      nodeSelector:
        #remove and add node annotation if running in non-development
        #sustainable-computing.io/kepler: ""
        kubernetes.io/os: linux
      serviceAccountName: kepler-sa
      containers:
      - name: kepler-exporter
        image: quay.io/sustainable_computing_io/kepler:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
        securityContext:
          privileged: true
        command:
        - /usr/bin/kepler
        - -address
        - 0.0.0.0:9102
        - -enable-gpu=true
        ports:
        - containerPort: 9102
          name: kepler-exporter
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /sys
          name: tracing
        - name: kernel-src
          mountPath: /usr/src/kernels
        - name: kernel-debug
          mountPath: /sys/kernel/debug
        - mountPath: /proc
          name: proc
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: tracing
        hostPath:
          path: /sys
          type: Directory
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory
      - name: kernel-src
        hostPath:
          path: /usr/src/kernels
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: kepler-exporter
  namespace: kepler
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
spec:
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
  ports:
  - name: kepler-exporter
    port: 9102
    targetPort: kepler-exporter
