global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: kepler

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: prometheus
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [localhost:9090]

# Load rules once and periodically evaluate them according to
# the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/rules/*.yaml
  - /etc/prometheus/rules/*.yml

# additional scrape configs
scrape_config_files:
  - /etc/prometheus/scrape-configs/*.yaml
  - /etc/prometheus/scrape-configs/*.yml

  # NOTE:  e.g. to add more jobs to scrape a
  # VM with IP 192.168.122.78 on port 8888,
  # - job_name: 'vm'
  #   static_configs:
  #     - targets: ['192.168.122.100:8888']
