apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler-model-server-cfm
  namespace: system
data:
  PROM_SERVER: 'http://prometheus-k8s.monitoring.svc.cluster.local:9090'
  PROM_QUERY_INTERVAL: '20'
  PROM_QUERY_STEP: '3'
  PROM_HEADERS: ''
  PROM_SSL_DISABLE: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-model-server
  namespace: system
spec:
  template:
    spec:
      volumes:
      - emptyDir: {}
        name: tmp
      containers:
      - name: server-api
      - name: online-trainer
        image: kepler-model-server:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: cfm
            mountPath: /etc/kepler/kepler.config
            readOnly: true
          - name: model-data
            mountPath: /data
            readOnly: false
          - name: tmp
            mountPath: /tmp
            readOnly: false
        command: ["python3.8",  "online_trainer.py"]