apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-model-server
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: server-api
      - name: online-trainer
        securityContext:
          privileged: true