apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler-cfm
  namespace: system
data:
  MODEL_SERVER_ENABLE: "true"
  MODEL_SERVER_ENDPOINT: http://kepler-model-server.$(MODEL_SERVER_NAMESPACE).cluster.local:$(MODEL_SERVER_PORT)/model
