apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-model-server
  namespace: system
spec:
  template:
    spec:
      serviceAccountName: kepler-sa
      containers:
        - name: server-api
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
              readOnly: false
      volumes:
        - name: tmp-volume
          emptyDir: {}
