# config file version
apiVersion: 1

datasources:
  # <string, required> name of the datasource. Required
  - name: kepler-prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: http://prometheus:9090
    isDefault: true
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
