apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sustainable-computing.io/app: kepler
  name: kepler-leader-election
  namespace: monitoring
rules:
  - apiGroups:
      - ''
    resources:
      - nodes/metrics # access /metrics/resource
      - nodes/proxy # access /pods
      - nodes/stats # access /pods
    verbs:
      - get
      - list
      - watch
  