apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Kepler exporter"
    openshift.io/display-name: ""
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler-exporter
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: kepler-exporter
        volumeMounts:
        - name: kernel-src
          mountPath: /usr/src/kernels
        - name: kernel-debug
          mountPath: /sys/kernel/debug
        securityContext:
          privileged: true
      volumes:      
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory
      - name: kernel-src
        hostPath:
          path: /usr/src/kernels
          type: Directory