apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler-cfm
  namespace: system
data:
  MODEL_CONFIG: |
    NODE_COMPONENTS_ESTIMATOR=true
    NODE_COMPONENTS_INIT_URL=https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/rapl/AbsPower/BPFOnly/GradientBoostingRegressorTrainer_1.zip
    NODE_TOTAL_ESTIMATOR=true
    NODE_TOTAL_INIT_URL=https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/acpi/AbsPower/BPFOnly/GradientBoostingRegressorTrainer_1.zip  
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler-exporter
  namespace: system
spec:
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        args:
        - until [ -e /tmp/estimator.sock ]; do sleep 1; done && /usr/bin/kepler -v=$(KEPLER_LOG_LEVEL) -kernel-source-dir=/usr/share/kepler/kernel_sources -redfish-cred-file-path=/etc/redfish/redfish.csv
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        name: kepler-exporter
      - image: kepler_model_server
        imagePullPolicy: IfNotPresent
        command: [ "python3.8" ]
        args: ["-u", "src/estimate/estimator.py" ]
        name: estimator
        volumeMounts:
        - name: cfm
          mountPath: /etc/kepler/kepler.config
          readOnly: true
        - mountPath: /tmp
          name: tmp
      volumes:
      - emptyDir: {}
        name: tmp