# This workflow will run mock-acpi compose on GH runner and run validator tool

name: Validate ACPI

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  validate-acpi:
    name: Validate ACPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Run mock-acpi compose
        working-directory: manifests/compose/mock-acpi
        run: |
          docker compose up -d

      - name: Warm up for 60 seconds
        run: |
          echo "Warm up for 60 seconds before running validator"
          sleep 60

      - name: Run mock-acpi validator tool
        working-directory: e2e/tools/validator
        run: |
          hatch run validator -f ./validator.mock-acpi.yaml validate-acpi -d 1m
