name: baseimage_dispatch

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  baseimagebuild:
    uses: ./.github/workflows/image_base.yml
    with:
      pushImage: true
    secrets:
      username: ${{ secrets.BOT_NAME }}
      password: ${{ secrets.BOT_TOKEN }}
