name: golang
# for golang basic checks with go command line tool
on:
  workflow_call:

permissions:
  contents: read

jobs:
  gofmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: run gofmt test
        run: ./automation/presubmit-tests/gofmt.sh

  escapes_detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: run escapes detect
        run: make escapes_detect

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2

  govet_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run go vet
        run: go vet ./...

  vulnerability_detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: run vulnerability detect
        run: make govulncheck