name: Deploy Kepler with Helm on a k8s Kind cluster

on:
  pull_request:

jobs:
  install-kepler-on-kind:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/marketplace/actions/kind-cluster
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      # https://github.com/Azure/setup-helm
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
      # Install the Kepler Helm chart to the previously deployed Kind cluster
      - name: Install the Helm chart
        run: helm install kepler ./ --namespace kepler --create-namespace
        working-directory: ./manifests/helm/kepler
      # Verify Kepler is up and running and show all resources in the namespace
      - name: Wait for rollout status of daemonset/kepler to be completed
        run: kubectl -n kepler rollout status daemonset/kepler
      - name: Show all Kubernetes resources from the kepler namespace
        run: kubectl -n kepler get all
