name: Push
on: # yamllint disable-line rule:truthy
  branch_protection_rule:
  push:
    branches: [main]
    paths-ignore:
      - doc/**
      - enhancements/**
      - "*.md"

jobs:
  # for each PR merge, trigger image build
  image:
    uses: ./.github/workflows/image.yml
    secrets:
      username: ${{ secrets.BOT_NAME }}
      password: ${{ secrets.BOT_TOKEN }}
  # for each PR merge, unit test for test coverage
  unit_test:
    uses: ./.github/workflows/unit_test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  # for each PR merge, openSSF scan
  scorecard:
    uses: ./.github/workflows/scorecard.yml
  # for each PR merge, go sec scan
  gosec:
    uses: ./.github/workflows/gosec.yml
