name: Daily Build Verification

on:
  schedule:
    - cron: 0 6 * * *  # UTC 6:00 AM
  push:
    branches: main
  pull_request:
    branches: main

env:
  # for token permission limits as id-token, just work for push or schedule
  SIGN: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}

permissions:
  id-token: write
  contents: read

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: anchore/sbom-action/download-syft@v0.18.0
      - uses: ./.github/build-image
        with:
          version: latest
          image_base: quay.io/sustainable_computing_io
          sign: ${{ env.SIGN }}

  verify-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: anchore/sbom-action/download-syft@v0.18.0
      - uses: ./.github/build-binary
        with:
          version: dev
          sign: ${{ env.SIGN }}

  verify-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v5
        with:
          version: latest
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: anchore/sbom-action/download-syft@v0.18.0
      - uses: ./.github/build-helm
        with:
          version: 0.0.0-dev
          sign: ${{ env.SIGN }}

      # do we have an helm registry to push to?
      #- name: Push Helm Chart to OCI
      #  shell: bash
      #  run: |
      #    CHART_VERSION="${VERSION#v}"
      #    helm push "helm-releases/kepler-helm-${CHART_VERSION}.tgz" "oci://${IMAGE_BASE}/charts"

      #- name: Sign OCI Helm Chart
      #  shell: bash
      #  run: |
      #    CHART_VERSION="${VERSION#v}"
      #    CHART_REF="${IMAGE_BASE}/charts/kepler-helm:${CHART_VERSION}"
      #    cosign sign "${CHART_REF}" --yes
