name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  build-image:
    if: github.repository_owner == 'sustainable-computing-io'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      IMG_BASE: quay.io/sustainable_computing_io
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: anchore/sbom-action/download-syft@v0.18.0
      - name: Login to registry
        run: echo "${{ secrets.BOT_TOKEN }}" | docker login -u "${{ secrets.BOT_NAME }}" --password-stdin $IMG_BASE
      - uses: ./.github/build-image
        with:
          version: ${{ github.ref_name }}
          image_base: ${{ env.IMG_BASE }}
      - name: Push image
        shell: bash
        run: make push VERSION=${{ github.ref_name }}
      - uses: actions/upload-artifact@v7
        with:
          name: image-artifacts
          retention-days: 1
          path: |
            image-kepler-*.spdx.json
            image-kepler-*.spdx.json.sigstore.json

  build-binary:
    if: github.repository_owner == 'sustainable-computing-io'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: anchore/sbom-action/download-syft@v0.18.0
      - uses: ./.github/build-binary
        with:
          version: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v7
        with:
          name: binary-artifacts
          retention-days: 1
          path: |
            bin/kepler-*.tar.gz
            bin/kepler-*.tar.gz.cert
            bin/kepler-*.tar.gz.sig
            bin/kepler-*.spdx.json
            bin/kepler-*.spdx.json.cert
            bin/kepler-*.spdx.json.sig

  build-helm:
    if: github.repository_owner == 'sustainable-computing-io'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      IMG_BASE: quay.io/sustainable_computing_io
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v5
        with:
          version: latest
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: anchore/sbom-action/download-syft@v0.18.0
      - name: Login to registry
        run: echo "${{ secrets.BOT_TOKEN }}" | docker login -u "${{ secrets.BOT_NAME }}" --password-stdin $IMG_BASE
      - uses: ./.github/build-helm
        with:
          version: ${{ github.ref_name }}

      - uses: actions/upload-artifact@v7
        with:
          name: helm-artifacts
          retention-days: 1
          path: |
            helm-releases/kepler-helm-*.tgz
            helm-releases/kepler-helm-*.tgz.cert
            helm-releases/kepler-helm-*.tgz.sig

  release:
    needs: [build-image, build-binary, build-helm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts/
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: release-${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          make_latest: true
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
