name: Close Stale Issues
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: 0 0 * * *  # Runs daily at midnight

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          # Message left when an issue/PR is first marked as stale
          stale-issue-message: This issue is stale because it has been open 60 days with no activity.
          stale-pr-message: This PR is stale because it has been open 60 days with no activity.

          # Configuration for marking as stale
          days-before-stale: 60
          days-before-issue-close: 7
          days-before-pr-close: -1

          # Labels to apply
          stale-issue-label: stale
          stale-pr-label: stale
