name: Unit test with bcc

on:
  pull_request:

jobs:
  unit_test_with_bcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test bcc in docker container
      run: sudo podman run --privileged -v $(pwd):/home -v /sys:/sys -v /lib/modules:/lib/modules -v /usr/src:/usr/src quay.io/sustainable_computing_io/kepler_builder:go1.18 bash -c "cd /home; export PATH=/usr/local/go/bin:$PATH; make test-verbose"
